### PR TITLE
DG-4 Reorganize Github Actions according to needs

### PR DESCRIPTION
**Pull request by nachiket-juneja**

### CODE REVIEW

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
Updating files:  40% (3897/9547)
Updating files:  41% (3915/9547)
Updating files:  41% (3950/9547)
Updating files:  42% (4010/9547)
Updating files:  42% (4058/9547)
Updating files:  43% (4106/9547)
Updating files:  44% (4201/9547)
Updating files:  45% (4297/9547)
error: unable to write file openmetadata-docs/images/v1.0/features/activity-feeds.gif
Updating files:  45% (4374/9547)
error: unable to write file openmetadata-docs/images/v1.0/features/add-descriptive-metadata.gif
Updating files:  45% (4375/9547)
error: unable to write file openmetadata-docs/images/v1.0/features/alerts-notifications/OMAlerts.gif
error: unable to write file openmetadata-docs/images/v1.0/features/all-your-data-in-one-place.gif
error: unable to write file openmetadata-docs/images/v1.0/features/complex-data-types.gif
error: unable to write file openmetadata-docs/images/v1.0/features/data-discovery-advanced-search.gif
error: unable to write file openmetadata-docs/images/v1.0/features/data-discovery-association.gif
error: unable to write file openmetadata-docs/images/v1.0/features/data-discovery-kw-search.gif
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/metadata-nav.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/most-active-users.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/most-viewed-assets.png: No space left on device
Updating files:  46% (4392/9547)
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/percentage-description.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/percentage-owner.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/total-data-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-insight/views-by-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-lineage.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/data-profiler.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/dbt-integration.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.0/features/deleted-entity.gif: No space left on device
fatal: cannot create directory at 'openmetadata-docs/images/v1.0/features/discovery-collaboration': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
Updating files:  40% (3898/9548)
Updating files:  41% (3915/9548)
Updating files:  42% (4011/9548)
Updating files:  42% (4062/9548)
Updating files:  43% (4106/9548)
Updating files:  44% (4202/9548)
Updating files:  45% (4297/9548)
Updating files:  46% (4393/9548)
Updating files:  46% (4400/9548)
Updating files:  47% (4488/9548)
Updating files:  47% (4494/9548)
Updating files:  48% (4584/9548)
Updating files:  49% (4679/9548)
Updating files:  50% (4774/9548)
Updating files:  51% (4870/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/add-descriptive-metadata.gif
Updating files:  51% (4935/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/all-your-data-in-one-place.gif
error: unable to write file openmetadata-docs/images/v1.1/features/complex-data-types.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-advanced-search.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-association.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery.gif
Updating files:  51% (4941/9548)
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/total-data-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/views-by-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-landing-page.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-lineage.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-profiler.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-versioning.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/dbt-integration.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/deleted-entity.gif: No space left on device
fatal: cannot create directory at 'openmetadata-docs/images/v1.1/features/discovery-collaboration': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
Updating files:  40% (3898/9548)
Updating files:  41% (3915/9548)
Updating files:  42% (4011/9548)
Updating files:  42% (4066/9548)
Updating files:  43% (4106/9548)
Updating files:  44% (4202/9548)
Updating files:  45% (4297/9548)
Updating files:  46% (4393/9548)
Updating files:  46% (4401/9548)
Updating files:  47% (4488/9548)
Updating files:  47% (4497/9548)
Updating files:  48% (4584/9548)
Updating files:  49% (4679/9548)
Updating files:  50% (4774/9548)
Updating files:  51% (4870/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/add-descriptive-metadata.gif
Updating files:  51% (4935/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/all-your-data-in-one-place.gif
error: unable to write file openmetadata-docs/images/v1.1/features/complex-data-types.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-advanced-search.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-association.gif
Updating files:  51% (4940/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery.gif
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/percentage-description.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/percentage-owner.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/total-data-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/views-by-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-landing-page.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-lineage.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-profiler.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-versioning.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/dbt-integration.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/deleted-entity.gif: No space left on device
fatal: cannot create directory at 'openmetadata-docs/images/v1.1/features/discovery-collaboration': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
Updating files:  40% (3898/9548)
Updating files:  41% (3915/9548)
Updating files:  42% (4011/9548)
Updating files:  42% (4076/9548)
Updating files:  43% (4106/9548)
Updating files:  44% (4202/9548)
Updating files:  45% (4297/9548)
Updating files:  46% (4393/9548)
Updating files:  46% (4400/9548)
Updating files:  47% (4488/9548)
Updating files:  47% (4494/9548)
Updating files:  48% (4584/9548)
Updating files:  49% (4679/9548)
Updating files:  50% (4774/9548)
Updating files:  51% (4870/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/add-descriptive-metadata.gif
Updating files:  51% (4935/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/all-your-data-in-one-place.gif
error: unable to write file openmetadata-docs/images/v1.1/features/complex-data-types.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-advanced-search.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-association.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery.gif
Updating files:  51% (4941/9548)
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/percentage-description.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/percentage-owner.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/total-data-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/views-by-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-landing-page.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-lineage.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-profiler.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-versioning.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/dbt-integration.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/deleted-entity.gif: No space left on device
fatal: cannot create directory at 'openmetadata-docs/images/v1.1/features/discovery-collaboration': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

: exit status 128
```

**Comment by srv-nucleusteq** [comment]
**Plan Error**
```
running git clone --branch techdebt/DG-4_reorganize_github_actions --depth=1 --single-branch https://srv-nucleusteq:<redacted>@github.com/nt-nuodata/nuodata-governance.git /home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default: Cloning into '/home/atlantis/.atlantis/repos/nt-nuodata/nuodata-governance/3/default'...
Updating files:  40% (3898/9548)
Updating files:  41% (3915/9548)
Updating files:  42% (4011/9548)
Updating files:  42% (4069/9548)
Updating files:  43% (4106/9548)
Updating files:  44% (4202/9548)
Updating files:  45% (4297/9548)
Updating files:  46% (4393/9548)
Updating files:  46% (4401/9548)
Updating files:  47% (4488/9548)
Updating files:  47% (4497/9548)
Updating files:  48% (4584/9548)
Updating files:  49% (4679/9548)
Updating files:  50% (4774/9548)
Updating files:  51% (4870/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/add-descriptive-metadata.gif
Updating files:  51% (4935/9548)
error: unable to write file openmetadata-docs/images/v1.1/features/all-your-data-in-one-place.gif
error: unable to write file openmetadata-docs/images/v1.1/features/complex-data-types.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-advanced-search.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery-association.gif
error: unable to write file openmetadata-docs/images/v1.1/features/data-discovery.gif
Updating files:  51% (4941/9548)
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/data-insight-kpi.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/metadata-nav.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/most-active-users.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/most-viewed-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/percentage-description.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/percentage-owner.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/total-data-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-insight/views-by-assets.png: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-landing-page.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-lineage.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-profiler.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/data-versioning.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/dbt-integration.gif: No space left on device
error: unable to create file openmetadata-docs/images/v1.1/features/deleted-entity.gif: No space left on device
fatal: cannot create directory at 'openmetadata-docs/images/v1.1/features/discovery-collaboration': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

: exit status 128
```

**Comment by nachiket-juneja** [comment]
[//]: <> (infracost-comment, valid-at=2023-11-28T11:01:17Z)

<h3>Infracost report</h3>
<h4>💰 Monthly cost will not change</h4>
<sub>This comment will be updated when code changes.
</sub>

**Pull request merged**
